php:
  build: .
  dockerfile: Dockerfile-php
  container_name: php
  volumes:
    - .:/var/www/laravel
  working_dir: /var/www/laravel
  entrypoint:
    - php-fpm

mysql:
  container_name: database
  image: "mysql"
  ports:
    - "3306:3306"
  environment:
    MYSQL_USER: laravel
    MYSQL_DATABASE: laravel
    MYSQL_PASSWORD: laravel
    MYSQL_ROOT_PASSWORD: root

nginx:
  container_name: nginx
  image: "nginx"
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - php
  links:
    - php
  ports:
    - "80:80"